services:
  iwr-communication:
    image: iwr-main-image
    container_name: iwr-communication
    build:
      context: .
      args: 
        BASE_IMG: ros:foxy
    network_mode: host
    entrypoint: ["/bin/bash", "-c", "source /opt/ros/foxy/setup.bash && source install/setup.bash && ros2 launch kmr_communication sunrise_communication.launch.py"]
    
  iwr-keyboard-control:
    container_name: iwr-keyboard-control
    image: iwr-main-image
    network_mode: host
    depends_on:
      - iwr-communication
    entrypoint: ["/bin/bash", "-c", "source /opt/ros/foxy/setup.bash && ros2 run teleop_twist_keyboard teleop_twist_keyboard"]