version: '3.9'

services:
  iwr-communication:
    image: iwr-main-image
    container_name: iwr-communication
    entrypoint: ["/bin/bash", "-c", "source /opt/ros/foxy/setup.bash && source install/setup.bash && ros2 launch kmr_communication sunrise_communication.launch.py"]
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        BASE_IMG: ros:foxy
        ROS_DISTRO: foxy
    network_mode: host
    ipc: host

  iwr-keyboard-control:
    image: iwr-main-image
    container_name: iwr-keyboard-control
    entrypoint: ["/bin/bash", "-c", "source /opt/ros/foxy/setup.bash && ros2 run teleop_twist_keyboard teleop_twist_keyboard"]
    network_mode: host
    ipc: host
    stdin_open: true
    tty: true
    depends_on:
      - iwr-communication

  iwr-navigation:
    image: iwr-main-image
    container_name: iwr-navigation
    environment:
      - DISPLAY=$DISPLAY
      - GUI=true
    entrypoint: ["/bin/bash", "-c", "source /opt/ros/foxy/setup.bash && source install/setup.bash && ros2 launch kmr_navigation2 navigation2.launch.py "]
    network_mode: host
    ipc: host
    stdin_open: true
    tty: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    depends_on:
      - iwr-communication
      - iwr-keyboard-control
